services:
  attendance-service:
    build: .
    container_name: attendance-service
    env_file:
      - .env
    ports:
      - "8100:8100"
    depends_on:
      - postgres
      - redis
    networks:
      - attendance_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery-worker:
    build: .
    container_name: attendance-celery
    env_file:
      - .env
    command: uv run celery -A src.configs.celery_config.celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - attendance_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: attendance-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance_net
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: attendance-redis
    networks:
      - attendance_net
    ports:
      - "6379:6379"

networks:
  attendance_net:

volumes:
  postgres_data:
